Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).



In [115]:
import numpy as np

In [47]:
n = int(input("Введите число:"))

Введите число:10


In [34]:
np.arange((n-1), 0-1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.


In [99]:
n = int(input("Введите число:"))

Введите число:5


In [100]:
reverse_array = np.arange((n-1), 0-1, -1)
reverse_array

array([4, 3, 2, 1, 0])

In [101]:
np.diag(reverse_array)

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [102]:
sum_ = sum(reverse_array)
print('Сумма значений по диагонали:', sum_)

Сумма значений по диагонали: 10


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [62]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [60]:
from numpy import linalg

In [61]:
linalg.solve(a, b)

array([ 0.06666667,  3.97777778, -4.22222222])

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем: 

In [265]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


На сайт заходит очередной посетитель, о покупках которого известно следующее:
In [ ]:

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [267]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [270]:
# пробую с enumerate

new_list = []

for row, val in enumerate(users_stats, 0):
    c = cosine(val, next_user_stats )
    
    
    new_list.append(c)

print('Лучшее совпадение:',max(new_list), 'Для пользователя ID:', new_list.index(max(new_list))) 

    


Лучшее совпадение: 0.9486832980505138 Для пользователя ID: 7


In [163]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )